-- Gamification v3.0 Schema Migration for Users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS lifetime_xp INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS monthly_xp INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_days INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_log_streak_days INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_log_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_freeze_held BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_freeze_queued BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_daily_xp_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_xp_from_log INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_xp_from_quiz INT DEFAULT 0;
